apiVersion: v2
name: datahub-executor-worker
description: A Helm chart for datahub-executor-worker
type: application
version: 0.0.29
appVersion: 0.3.15.4
maintainers:
  - name: DataHub
    email: datahub@acryl.io
